-- 02_seed_data.sql
-- Realistic supply chain seed data based on the Kaggle Supply Chain Analysis dataset structure.
-- Products are from the beauty/personal care vertical (matches the public dataset).
--
-- NOTE: Embeddings are NOT seeded here — they're generated by the Python seed script
-- (data/seeds/generate_embeddings.py) which calls OpenAI and writes back to Postgres.
-- This file only seeds the structured/relational data.

-- ─────────────────────────────────────────────
-- PRODUCTS
-- ─────────────────────────────────────────────
INSERT INTO products (product_id, product_name, category, price) VALUES
    ('SKU-001', 'Moisturizing Face Cream',     'skincare',  14.99),
    ('SKU-002', 'Vitamin C Serum',             'skincare',  24.99),
    ('SKU-003', 'Hydrating Shampoo',           'haircare',   9.99),
    ('SKU-004', 'Keratin Hair Mask',           'haircare',  19.99),
    ('SKU-005', 'Matte Lipstick',              'cosmetics',  8.99),
    ('SKU-006', 'Foundation SPF30',            'cosmetics', 29.99),
    ('SKU-007', 'Eye Shadow Palette',          'cosmetics', 34.99),
    ('SKU-008', 'Sunscreen SPF50',             'skincare',  18.99),
    ('SKU-009', 'Body Lotion',                 'skincare',  11.99),
    ('SKU-010', 'Conditioner Argan Oil',       'haircare',  12.99)
ON CONFLICT (product_id) DO NOTHING;

-- ─────────────────────────────────────────────
-- SUPPLIERS
-- ─────────────────────────────────────────────
INSERT INTO suppliers (supplier_id, supplier_name, location, lead_time_days, defect_rate) VALUES
    ('SUP-001', 'Kolkata Cosmetics Co.',    'Kolkata',  15, 0.0200),
    ('SUP-002', 'Mumbai Beauty Works',      'Mumbai',   12, 0.0150),
    ('SUP-003', 'Chennai Chem Labs',        'Chennai',  18, 0.0280),
    ('SUP-004', 'Delhi Packaging Ltd.',     'Delhi',    10, 0.0120),
    ('SUP-005', 'Bangalore Bio Products',   'Bangalore', 8, 0.0180)
ON CONFLICT (supplier_id) DO NOTHING;

-- ─────────────────────────────────────────────
-- INVENTORY (current stock levels)
-- ─────────────────────────────────────────────
INSERT INTO inventory (product_id, location, stock_level, reorder_point, max_capacity) VALUES
    ('SKU-001', 'Northeast',  450, 100, 1000),
    ('SKU-001', 'Southeast',   80, 100, 1000),  -- ← BELOW reorder point! stockout risk
    ('SKU-002', 'Northeast',  320, 150, 800),
    ('SKU-002', 'Southeast',  210, 150, 800),
    ('SKU-003', 'West',       600, 200, 1200),
    ('SKU-004', 'West',        95, 150, 600),   -- ← BELOW reorder point!
    ('SKU-005', 'Northeast',  750, 200, 1500),
    ('SKU-006', 'Southeast',  180, 200, 900),   -- ← BELOW reorder point!
    ('SKU-007', 'Midwest',    420, 150, 900),
    ('SKU-008', 'Southeast',  230, 100, 800),
    ('SKU-009', 'West',       890, 300, 2000),
    ('SKU-010', 'Northeast',  110, 150, 700)    -- ← BELOW reorder point!
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────
-- SUPPLY CHAIN RECORDS (transaction history)
--
-- 30 representative records covering different regions, products, dates.
-- In real use you'd load 10k+ rows from Kaggle.
-- ─────────────────────────────────────────────
INSERT INTO supply_chain_records
    (product_id, supplier_id, order_quantity, order_date, ship_date, delivery_date,
     shipping_costs, manufacturing_costs, revenue, region, customer_segment)
VALUES
    ('SKU-001','SUP-001', 500,'2024-01-05','2024-01-10','2024-01-20',  250.00, 3500.00,  7500.00,'Northeast','retail'),
    ('SKU-001','SUP-001', 300,'2024-02-01','2024-02-06','2024-02-18',  180.00, 2100.00,  4500.00,'Southeast','retail'),
    ('SKU-002','SUP-002', 200,'2024-01-10','2024-01-15','2024-01-25',  320.00, 2800.00,  5000.00,'Northeast','wholesale'),
    ('SKU-002','SUP-002', 150,'2024-02-15','2024-02-20','2024-03-03',  210.00, 2100.00,  3750.00,'Southeast','retail'),
    ('SKU-003','SUP-003', 800,'2024-01-03','2024-01-08','2024-01-26',  400.00, 4800.00,  7992.00,'West','retail'),
    ('SKU-003','SUP-003', 400,'2024-03-01','2024-03-06','2024-03-24',  200.00, 2400.00,  3996.00,'Northeast','wholesale'),
    ('SKU-004','SUP-004', 250,'2024-01-20','2024-01-25','2024-02-04',  300.00, 2750.00,  4997.50,'West','retail'),
    ('SKU-004','SUP-004', 180,'2024-03-10','2024-03-15','2024-03-25',  220.00, 1980.00,  3599.40,'Midwest','retail'),
    ('SKU-005','SUP-001', 600,'2024-01-15','2024-01-20','2024-02-04',  150.00, 2400.00,  5394.00,'Northeast','retail'),
    ('SKU-005','SUP-001', 450,'2024-02-20','2024-02-25','2024-03-11',  130.00, 1800.00,  4045.50,'Southeast','wholesale'),
    ('SKU-006','SUP-002', 300,'2024-01-08','2024-01-13','2024-01-25',  450.00, 6000.00,  8997.00,'Southeast','retail'),
    ('SKU-006','SUP-002', 200,'2024-02-10','2024-02-15','2024-02-27',  300.00, 4000.00,  5998.00,'Northeast','wholesale'),
    ('SKU-007','SUP-003', 350,'2024-01-22','2024-01-27','2024-02-14',  525.00, 8750.00, 12246.50,'Midwest','retail'),
    ('SKU-007','SUP-003', 250,'2024-03-05','2024-03-10','2024-03-28',  375.00, 6250.00,  8747.50,'Northeast','wholesale'),
    ('SKU-008','SUP-004', 400,'2024-02-01','2024-02-06','2024-02-16',  280.00, 4400.00,  7596.00,'Southeast','retail'),
    ('SKU-008','SUP-001', 300,'2024-03-15','2024-03-20','2024-03-30',  210.00, 3300.00,  5697.00,'West','retail'),
    ('SKU-009','SUP-005', 700,'2024-01-10','2024-01-15','2024-01-23',  280.00, 4900.00,  8393.00,'West','wholesale'),
    ('SKU-009','SUP-005', 500,'2024-02-25','2024-03-01','2024-03-09',  200.00, 3500.00,  5995.00,'Midwest','retail'),
    ('SKU-010','SUP-002', 400,'2024-01-18','2024-01-23','2024-02-04',  260.00, 3200.00,  5196.00,'Northeast','retail'),
    ('SKU-010','SUP-002', 280,'2024-03-08','2024-03-13','2024-03-23',  182.00, 2240.00,  3637.20,'Southeast','wholesale'),
    -- More records for seasonal analysis
    ('SKU-001','SUP-001', 600,'2024-06-01','2024-06-06','2024-06-21',  300.00, 4200.00,  8994.00,'Southeast','retail'),
    ('SKU-008','SUP-004', 800,'2024-06-15','2024-06-20','2024-06-30',  560.00, 8800.00, 15192.00,'Southeast','retail'), -- summer sunscreen spike
    ('SKU-008','SUP-001', 650,'2024-07-01','2024-07-06','2024-07-16',  455.00, 7150.00, 12343.50,'West','retail'),
    ('SKU-002','SUP-002', 350,'2024-06-10','2024-06-15','2024-06-27',  560.00, 4900.00,  8746.50,'Northeast','wholesale'),
    ('SKU-005','SUP-001',1000,'2024-11-20','2024-11-25','2024-12-10',  250.00, 4000.00,  8990.00,'Northeast','retail'), -- holiday lipstick spike
    ('SKU-006','SUP-002', 500,'2024-11-25','2024-11-30','2024-12-15',  750.00,10000.00, 14995.00,'Southeast','retail'),
    ('SKU-007','SUP-003', 600,'2024-12-01','2024-12-06','2024-12-20', 900.00, 15000.00, 20994.00,'Northeast','wholesale'),
    ('SKU-003','SUP-003', 900,'2024-09-05','2024-09-10','2024-09-28',  450.00, 5400.00,  8991.00,'West','retail'),
    ('SKU-004','SUP-004', 300,'2024-09-15','2024-09-20','2024-09-30',  360.00, 3300.00,  5997.00,'Northeast','retail'),
    ('SKU-009','SUP-005', 800,'2024-10-10','2024-10-15','2024-10-23',  320.00, 5600.00,  9592.00,'Midwest','wholesale')
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────
-- TSVECTOR: populate search_vector column
--
-- WHY do this in SQL and not in the app?
-- It's faster to let Postgres compute tsvector during the seed.
-- We concatenate product_id, region, customer_segment, and any text fields
-- into one searchable text blob, then convert to tsvector.
--
-- to_tsvector('english', ...) applies English stemming:
--   "moisturizing" → "moistur", "retail" → "retail"
-- This means searching "moisturize" finds "moisturizing" records.
-- ─────────────────────────────────────────────
UPDATE supply_chain_records scr
SET search_vector = to_tsvector(
    'english',
    COALESCE(p.product_name, '') || ' ' ||
    COALESCE(p.category, '') || ' ' ||
    COALESCE(scr.region, '') || ' ' ||
    COALESCE(scr.customer_segment, '') || ' ' ||
    COALESCE(scr.product_id, '')
)
FROM products p
WHERE scr.product_id = p.product_id;

-- ─────────────────────────────────────────────
-- FORECAST METRICS (MAPE data for Forecasting Analyst agent)
--
-- Some products intentionally have high MAPE (>15%) — the agent will find these
-- and propose hyperparameter changes.
-- ─────────────────────────────────────────────
INSERT INTO forecast_metrics
    (product_id, run_date, model_name, mape, mae, hyperparameters, notes)
VALUES
    ('SKU-001','2024-03-31','xgboost_v1', 0.0821,  45.20, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'Good performance, skincare stable demand'),
    ('SKU-002','2024-03-31','xgboost_v1', 0.1234,  68.40, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'Moderate error, seasonal spikes missed'),
    ('SKU-003','2024-03-31','xgboost_v1', 0.0654,  87.30, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'Low error, high volume product'),
    ('SKU-004','2024-03-31','xgboost_v1', 0.2341, 124.60, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'HIGH ERROR: underforecasting Q3 demand'),
    ('SKU-005','2024-03-31','xgboost_v1', 0.1876, 112.80, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'HIGH ERROR: holiday spike not captured'),
    ('SKU-006','2024-03-31','xgboost_v1', 0.0923,  98.40, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'Acceptable, slight underfit'),
    ('SKU-007','2024-03-31','xgboost_v1', 0.1102, 145.20, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'Moderate, holiday demand variable'),
    ('SKU-008','2024-03-31','xgboost_v1', 0.2789, 198.60, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'HIGH ERROR: summer seasonality not modeled'),
    ('SKU-009','2024-03-31','xgboost_v1', 0.0712,  94.30, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'Good, stable demand profile'),
    ('SKU-010','2024-03-31','xgboost_v1', 0.1543, 102.10, '{"n_estimators":100,"max_depth":6,"learning_rate":0.1}',  'Moderate error, regional variation high')
ON CONFLICT DO NOTHING;
